In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import os
os.getcwd()


'/content'

In [0]:
os.chdir('/content/drive/My Drive/deep learning')

In [0]:
import pandas as pd
train_data = pd.read_csv("iris_training.csv")
test_data=pd.read_csv("iris_test.csv")

In [6]:
train_data.shape

(120, 5)

In [7]:
test_data.shape

(30, 5)

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
features1 = train_data.iloc[:, :-1].values
labels1 = train_data.iloc[:, -1:].values

In [0]:
features2=test_data.iloc[:,:-1].values
labels2=test_data.iloc[:,-1].values

In [12]:
from sklearn.linear_model import LogisticRegression
reg3 = LogisticRegression()
reg3.fit(features1, labels1)
# Predicting the Test set results
labels_pred2 = reg3.predict(features2)
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels2, labels_pred2)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [15]:
cm

array([[ 8,  0,  0],
       [ 0, 12,  2],
       [ 0,  0,  8]])

In [0]:
probability = reg3.predict_proba(features2)


In [0]:
probability

In [16]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
classifier = Sequential()

In [18]:
features1.shape

(120, 4)

In [0]:
#adding the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 4))


# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 3, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [0]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder(categorical_features = [0])
labels1 = onehotencoder.fit_transform(labels1).toarray()

In [0]:
classifier.fit(features1, labels1, batch_size = 120, epochs = 1000)

In [54]:
labels_pred = classifier.predict(features2)
pred = np.argmax(labels_pred, axis=1)

array([1, 2, 0, 1, 1, 1, 0, 1, 1, 2, 2, 0, 2, 1, 1, 0, 1, 0, 0, 2, 0, 1,
       2, 1, 1, 1, 0, 1, 2, 1])

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels2, pred)

In [56]:
cm

array([[ 8,  0,  0],
       [ 0, 14,  0],
       [ 0,  1,  7]])